name: medmnist_bn_128
seed: 1234
track: &track False
model:
  class_name: CSNN
  module_name: src.models.csnn
  parameters:
    in_channels: 1
    out_channels: 2
    img_size: &img_size 128
    n_steps: 5
    encoding_method: direct
dataloader:
  class_name: BreastMNISTDataloader
  module_name: src.data.loaders.BreastMNIST
  parameters:
    data_dir: ./data
    image_size: *img_size
    batch_size: 8
    num_workers: 4
    debug: False

trainer:
  class_name: medmnistTrainer
  module_name: tasks.medmnist.trainer
  parameters:
    num_epochs: 10
    early_stopping_patience: 5
    lr_scheduler: null
    lr: 0.00002
    weight_decay: 0.00001
    track: *track
    loss:
      class_name: MSELoss
      module_name: torch.nn
      parameters:
experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
