name: fashionmnist_bn
seed: 1234
track: &track False
model:
  class_name: CSNN
  module_name: src.models.csnn
  parameters:
    in_channels: 1
    out_channels: 10
    img_size: &img_size 28
    n_steps: 5
    encoding_method: direct
dataloader:
  class_name: DefaultDataloader
  module_name: src.data.loaders.default
  parameters:
    data_dir: ./data
    batch_size: 32
    num_workers: 8
    debug: False

trainer:
  class_name: FashionMNISTTrainer
  module_name: tasks.snn.fmnist.trainer
  parameters:
    num_epochs: 100
    early_stopping_patience: 100
    lr_scheduler: null
    lr: 0.0001
    weight_decay: 0.
    track: *track
    loss:
      class_name: MSELoss
      module_name: torch.nn
      parameters:
experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
